-- SJP FORUM DATABASE SETUP
-- Run this entire script once in Supabase SQL Editor.
-- It creates the forum tables, roles, RLS policies, and moderation log.

create extension if not exists pgcrypto;

create type public.sjp_role as enum ('admin','moderator','forum_handler','member');

create table if not exists public.forum_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 2 and 80),
  role public.sjp_role not null default 'member',
  created_at timestamptz not null default now()
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.forum_profiles(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 3 and 160),
  body text not null check (char_length(trim(body)) between 1 and 10000),
  category text not null default 'General' check (category in ('General','Suggestions','Problems & Issues','Discussion','Announcements')),
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  author_id uuid not null references public.forum_profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 5000),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_likes (
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  user_id uuid not null references public.forum_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id,user_id)
);

create table if not exists public.forum_reports (
  id bigint generated by default as identity primary key,
  post_id bigint references public.forum_posts(id) on delete cascade,
  comment_id bigint references public.forum_comments(id) on delete cascade,
  reporter_id uuid not null references public.forum_profiles(id) on delete cascade,
  reason text not null check (char_length(trim(reason)) between 3 and 500),
  status text not null default 'open' check (status in ('open','reviewed','dismissed')),
  created_at timestamptz not null default now(),
  check ((post_id is not null) <> (comment_id is not null))
);

create table if not exists public.forum_moderation_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.forum_profiles(id) on delete cascade,
  action text not null,
  target_type text not null,
  target_id bigint,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists forum_posts_created_at_idx on public.forum_posts(created_at desc);
create index if not exists forum_posts_category_idx on public.forum_posts(category);
create index if not exists forum_comments_post_id_idx on public.forum_comments(post_id);
create index if not exists forum_reports_status_idx on public.forum_reports(status);

create or replace function public.is_forum_staff()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.forum_profiles where id = auth.uid() and role in ('admin','moderator','forum_handler')); $$;

create or replace function public.is_forum_mod()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.forum_profiles where id = auth.uid() and role in ('admin','moderator')); $$;

create or replace function public.is_forum_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.forum_profiles where id = auth.uid() and role = 'admin'); $$;

alter table public.forum_profiles enable row level security;
alter table public.forum_posts enable row level security;
alter table public.forum_comments enable row level security;
alter table public.forum_likes enable row level security;
alter table public.forum_reports enable row level security;
alter table public.forum_moderation_logs enable row level security;

drop policy if exists "Profiles are publicly readable" on public.forum_profiles;
create policy "Profiles are publicly readable" on public.forum_profiles for select using (true);

drop policy if exists "Users create own profile" on public.forum_profiles;
create policy "Users create own profile" on public.forum_profiles for insert with check (id = auth.uid());

drop policy if exists "Users update own profile" on public.forum_profiles;
create policy "Users update own profile" on public.forum_profiles for update using (id = auth.uid() or public.is_forum_admin()) with check (id = auth.uid() or public.is_forum_admin());

drop policy if exists "Visible posts are readable" on public.forum_posts;
create policy "Visible posts are readable" on public.forum_posts for select using (is_hidden = false or public.is_forum_staff());

drop policy if exists "Members create posts" on public.forum_posts;
create policy "Members create posts" on public.forum_posts for insert with check (author_id = auth.uid());

drop policy if exists "Authors edit own posts" on public.forum_posts;
create policy "Authors edit own posts" on public.forum_posts for update using (author_id = auth.uid() or public.is_forum_staff()) with check (author_id = auth.uid() or public.is_forum_staff());

drop policy if exists "Authors or staff delete posts" on public.forum_posts;
create policy "Authors or staff delete posts" on public.forum_posts for delete using (author_id = auth.uid() or public.is_forum_staff());

drop policy if exists "Visible comments are readable" on public.forum_comments;
create policy "Visible comments are readable" on public.forum_comments for select using (is_hidden = false or public.is_forum_staff());

drop policy if exists "Members create comments" on public.forum_comments;
create policy "Members create comments" on public.forum_comments for insert with check (author_id = auth.uid() and not exists (select 1 from public.forum_posts p where p.id = post_id and p.is_locked));

drop policy if exists "Authors or staff update comments" on public.forum_comments;
create policy "Authors or staff update comments" on public.forum_comments for update using (author_id = auth.uid() or public.is_forum_staff()) with check (author_id = auth.uid() or public.is_forum_staff());

drop policy if exists "Authors or staff delete comments" on public.forum_comments;
create policy "Authors or staff delete comments" on public.forum_comments for delete using (author_id = auth.uid() or public.is_forum_staff());

drop policy if exists "Likes are readable" on public.forum_likes;
create policy "Likes are readable" on public.forum_likes for select using (true);

drop policy if exists "Users manage own likes" on public.forum_likes;
create policy "Users manage own likes" on public.forum_likes for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "Users create reports" on public.forum_reports;
create policy "Users create reports" on public.forum_reports for insert with check (reporter_id = auth.uid());

drop policy if exists "Users see own reports or staff see all" on public.forum_reports;
create policy "Users see own reports or staff see all" on public.forum_reports for select using (reporter_id = auth.uid() or public.is_forum_staff());

drop policy if exists "Staff manage reports" on public.forum_reports;
create policy "Staff manage reports" on public.forum_reports for update using (public.is_forum_staff()) with check (public.is_forum_staff());

drop policy if exists "Staff read moderation logs" on public.forum_moderation_logs;
create policy "Staff read moderation logs" on public.forum_moderation_logs for select using (public.is_forum_staff());

drop policy if exists "Staff create moderation logs" on public.forum_moderation_logs;
create policy "Staff create moderation logs" on public.forum_moderation_logs for insert with check (actor_id = auth.uid() and public.is_forum_staff());

-- After creating your first forum account, promote it manually in the Table Editor:
-- update public.forum_profiles set role = 'admin' where id = 'YOUR-AUTH-USER-UUID';
